// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlkwqrbqvtwxnkfsleqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsa3dxcmJxdnR3eG5rZnNsZXFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MjgyNjQsImV4cCI6MjA3NDQwNDI2NH0.NS0oaEGgyyk668nqlbu03oGBkCYDYIi7BAXvLILp_pc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});